project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - Data Visualization.qmd
      - reflection.qmd

format:
  html:
    theme: lux
    css: bootstrap.min.css
    toc: true



