project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    left:
      - about.qmd
      - relfection.qmd
      - Data Visualization.qmd

format:
  html:
    theme: lux
    css: bootstrap.min.css
    toc: true



